"""add title to image_content

Revision ID: 2a6036ce1ee2
Revises: cb41b2a11c01
Create Date: 2025-10-04 00:40:00.058495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a6036ce1ee2"
down_revision: Union[str, Sequence[str], None] = "cb41b2a11c01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image_contents",
        sa.Column(
            "title", sa.String(length=200), nullable=False, server_default="Untitled"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("image_contents", "title")
    # ### end Alembic commands ###
