"""drop test tables

Revision ID: cb41b2a11c01
Revises: 864adfc086b8
Create Date: 2025-10-03 23:27:10.571297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb41b2a11c01"
down_revision: Union[str, Sequence[str], None] = "864adfc086b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artworks_id"), table_name="artworks")
    op.drop_table("artworks")
    op.drop_index(op.f("ix_artists_id"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artworks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("year_created", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("medium", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "dimensions", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "image_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("artist_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"], ["artists.id"], name=op.f("artworks_artist_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("artworks_pkey")),
    )
    op.create_index(op.f("ix_artworks_id"), "artworks", ["id"], unique=False)
    op.create_table(
        "artists",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("biography", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("death_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "nationality", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("artists_pkey")),
    )
    op.create_index(op.f("ix_artists_id"), "artists", ["id"], unique=False)
    # ### end Alembic commands ###
